### PR TITLE
Initial work on optics support for Cookie/Set-Cookie headers.

### PR DESCRIPTION
**Pull request by petejohanson**
* Closes xyncro/freya#197

Note: I did build this locally, but with additional local changes to build on Linux w/ only .NET Core 2.0 installed. If there are issues with your upstream standard build and this PR, please let me know.

### CODE REVIEW

**Comment by neoeinstein** [comment]
This looks good to me from a cursory review. I'll take a look tomorrow morning to verify everything is good here. If so, we'll get this merged in and published. Thanks for the PR!

**Comment by petejohanson** [comment]
@neoeinstein Thanks! It's been fun learning Freya so far.

**Comment by neoeinstein** [comment]
Now published on NuGet. Currently with the alpha-171018 pre-release tag. It's not included by the default "Freya" dependency right now, so you will need to depend on it seperately to pull in the optics.

**Review by neoeinstein — COMMENTED** [review]
Looks good.

**Comment by petejohanson** [comment]
Thanks!

**Pull request merged**
